#ifndef PERSIST_H
#define PERSIST_H
#include <stdio.h>

//Saves all the weights, biases and activations of all the layer's neurons into a text file
void SaveNeural();

//Sets the values of all weights, biases and activation 
//from a file in the format generated by SaveNeural
void LoadNeural();

#endif